#!/usr/bin/env bash

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

rector () {
  cat << 'EOF' > rector.php
<?php

declare(strict_types=1);

use Rector\CodingStyle\Rector\ClassLike\NewlineBetweenClassLikeStmtsRector;
use Rector\CodingStyle\Rector\Use_\SeparateMultiUseImportsRector;
use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\ArrowFunction\AddArrowFunctionReturnTypeRector;
use Rector\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictTypedCallRector;
use RectorLaravel\Rector\FuncCall\RemoveDumpDataDeadCodeRector;
use RectorLaravel\Set\LaravelSetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__.'/app',
        __DIR__.'/bootstrap/app.php',
        __DIR__.'/database',
        __DIR__.'/public',
    ])
    ->withSets([
        LaravelSetList::LARAVEL_CODE_QUALITY,
        LaravelSetList::LARAVEL_COLLECTION,
        LaravelSetList::LARAVEL_FACTORIES,
        LaravelSetList::LARAVEL_IF_HELPERS,
        LaravelSetList::LARAVEL_TYPE_DECLARATIONS,
    ])
    ->withPreparedSets(
        deadCode: true,
        codeQuality: true,
        codingStyle: true,
        typeDeclarations: true,
        privatization: true,
        earlyReturn: true,
    )
    ->withConfiguredRule(RemoveDumpDataDeadCodeRector::class, [
        'dd',
        'dump',
        'var_dump',
    ])
    ->withSkip([
        NewlineBetweenClassLikeStmtsRector::class,
        AddArrowFunctionReturnTypeRector::class,
        SeparateMultiUseImportsRector::class,
        ReturnTypeFromStrictTypedCallRector::class
    ]);
EOF
}

pint () {
  cat << 'EOF' > pint.json
{
  "preset": "laravel",
  "rules": {
    "declare_strict_types": true,
    "fully_qualified_strict_types": true,
    "global_namespace_import": {
      "import_classes": true,
      "import_constants": true,
      "import_functions": true
    },
    "mb_str_functions": true,
    "modernize_types_casting": true,
    "new_with_parentheses": false,
    "no_superfluous_elseif": true,
    "no_useless_else": true,
    "no_multiple_statements_per_line": true,
    "lowercase_keywords": true,
    "lowercase_static_reference": true,
    "array_push": true,
    "strict_comparison": true,
    "backtick_to_shell_exec": true
  }
}
EOF
}

phpstan () {
  cat << 'EOF' > phpstan.neon
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon

parameters:
    level: 6

    paths:
        - app/
EOF
}

license () {
  cat << 'EOF' > LICENSE
Copyright 2025 Mauricio Sousa

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without
restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
the Software is furnished to do so, subject to the following conditions:


The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
EOF
}

prettier () {
  cat << 'EOF' > .prettierrc
{
  "singleQuote": true,
  "plugins": ["@shufo/prettier-plugin-blade", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": ["*.blade.php"],
      "options": {
        "parser": "blade",
        "tabWidth": 4
      }
    }
  ],
  "tailwindStylesheet": "./resources/css/app.css"
}
EOF
}


app-service-provider () {
	cat <<- 'EOF' > app/Providers/AppServiceProvider.php
	<?php

	declare(strict_types=1);

	namespace App\Providers;

	use Illuminate\Database\Eloquent\Model;
	use Illuminate\Support\Facades\DB;
	use Illuminate\Support\Facades\Vite;
	use Illuminate\Support\ServiceProvider;

	class AppServiceProvider extends ServiceProvider
	{
		/**
		 * Register any application services.
		 */
		public function register(): void
		{
			$this->configureModels();
			$this->configureVite();
			$this->configureCommands();
		}

		/**
		 * Configure the application's commands.
		 */
		private function configureCommands(): void
		{
			DB::prohibitDestructiveCommands(
				$this->app->environment('production'),
			);
		}

		private function configureModels(): void
		{
			Model::shouldBeStrict(! $this->app->environment('production'));
		}

		private function configureVite(): void
		{
			Vite::useAggressivePrefetching();
		}

		/**
		 * Bootstrap any application services.
		 */
		public function boot(): void
		{
			//
		}
	}
	EOF
}

install_php_dependencies () {
  echo "Installing larastan, rector, rector for laravel and laravel ide helper"
  composer require --dev barryvdh/laravel-ide-helper driftingly/rector-laravel rector/rector larastan/larastan
  php artisan ide-helper:generate
  composer bump
  composer update
  echo "Done installing php dependencies"
}

install_node_dependencies () {
  echo "Installing node formatters"
  npm install --silent --save-dev prettier-plugin-tailwindcss
  npm install --silent --save-dev prettier
  npm install --silent --save-dev @shufo/prettier-plugin-blade
  npm update
  echo "Done installing node formatters"
}

forgejo-workflows () {
  echo "Creating forgejo workflows"
  
  mkdir -p .forgejo/workflows
  
cat << 'EOF' > .forgejo/workflows/larastan.yaml
  name: Larastan

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    larastan:
      runs-on: codeberg-tiny
      container:
        image: node:22-bookworm
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate Application key
        run: php artisan key:generate
      - name: Build Assets
        run: npm run build
      - name: Static Analysis check via larastan
        run: vendor/bin/phpstan analyse
EOF

cat << 'EOF' > .forgejo/workflows/lint.yaml
  name: Lint

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    linting:
      runs-on: codeberg-tiny
      container:
        image: node:22-bookworm
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate Application key
        run: php artisan key:generate
      - name: Build Assets
        run: npm run build
      - name: Run Pint
        run: vendor/bin/pint --test
      # - name: Run Prettier
        # run: npx prettier --check .
EOF

cat << 'EOF' > .forgejo/workflows/tests.yaml
  name: Tests

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    laravel-tests:
      runs-on: codeberg-tiny
      container:
        image: node:22-bookworm
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate Application key
        run: php artisan key:generate
      - name: Build Assets
        run: npm run build
      - name: Run Tests
        run: vendor/bin/pest --ci --parallel
EOF
    echo "Done!"
}

if [[ -d "vendor" ]]; then
    install_php_dependencies
    rector
    pint
    phpstan
    app-service-provider
    license
    forgejo-workflows
  if grep -q "inertiajs" "composer.json"; then
    update-composer-inertia
    echo "Updating node dependencies"
    npm update
    echo "Done!"
    exit 0
  fi
    install_node_dependencies
    update-composer
    update-package-json
    prettier
    echo "Done!"
  exit 0
else
  fatal "vendor not found! Exiting now..."
fi
